version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/ow2con24"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pnpm"
    directory: "/storybook-paris-3"
    schedule:
      interval: "weekly"
